inherit_from:
  - .rubocop_airbnb.yml
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/**/*'
    - 'vendor/**/*'

Lint/AssignmentInCondition:
  Enabled: false
Style/TrailingCommaInLiteral:
  Enabled: false
