entrypoint: bundle exec rackup --port $PORT
env: flex
runtime: ruby

env_variables:
  SECRET_KEY_BASE: 8155ef980d3f80cfc18aa42345f099dded589390cc585b2d1c8c92d7736fc5dbe8e594a61976126952bd43168c45acf27e39b8a17f039602e83056ab2d5b5be0

beta_settings:
  cloud_sql_instances: general-concert-0319:us-central1:general-concert-0319

steps:
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"
